### ISSUE TITLE
cannot run  node index.js

### ISSUE THREAD

**Issue by martumkung** [samuraitruong/coinmaster#19]
first when i run 
`node index.js`

i got error  
`Error: Cannot find module 'dotenv'`

then i run
`npm install`

after that i run
`node index.js`

again and it get this error
`(node:12136) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined`

please help

**Comment by overy0u** [comment]
cp env.sample .env
yarn install
run again , if you still cant use it i can help u

**Comment by fuatcoskun** [comment]
I have tried with two different node versions 12.19.0 and 14.14.0 but still getting the same error : 
```
(node:76872) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:120:11)
    at Object.join (path.js:1039:7)
    at new CoinMaster (/Users/fcoskun/Downloads/coinmaster-master/coinmaster.js:105:23)
    at /Users/fcoskun/Downloads/coinmaster-master/index.js:71:14
    at Object.<anonymous> (/Users/fcoskun/Downloads/coinmaster-master/index.js:81:3)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
(node:76872) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:76872) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

It was looking like "path" module is not installed and I have installed it manually by entering "yarn add path"
I have installed all dependencies using yarn and later tried with npm also. Nothing changed...
Do you suggest a specific node version or do you have any other suggestions to fix this problem?
